name: Build and push docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-backend:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from version.yaml
        run: |
          echo "VERSION=$(cat version.yaml | sed -n 's/version: //p')" >> $GITHUB_ENV
          echo $VERSION

      - name:  Set build tags based on branch
        run: |
          if [ $GITHUB_REF = 'refs/heads/main' ]; then
            echo "IMAGE_TAGS=$VERSION" >> $GITHUB_ENV
          else
            echo "IMAGE_TAGS=rc-$VERSION-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          fi

      - name:  Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: PR - Build and push image to GHCR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/heissonwillen/event-go:${{ env.IMAGE_TAGS }}
          annotations: |
            org.opencontainers.image.description=Event Go, Broadcast server sent events by sending HTTP calls.
          build-args: |
            VERSION=${{ env.VERSION }}
          labels: |
            org.opencontainers.image.source=https://github.com/heissonwillen/event-go
          cache-from: type=registry,ref=ghcr.io/heissonwillen/event-go:latest
          cache-to: type=registry,ref=ghcr.io/heissonwillen/event-go:latest

      - name: Main - Build and push image to GHCR and Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/heissonwillen/event-go:${{ env.IMAGE_TAGS }}
            heissonwillen/event-go:${{ env.IMAGE_TAGS }}
          annotations: |
            org.opencontainers.image.description=Event Go, Broadcast server sent events by sending HTTP calls.
          build-args: |
            VERSION=${{ env.VERSION }}
          labels: |
            org.opencontainers.image.source=https://github.com/heissonwillen/event-go
          cache-from: type=registry,ref=ghcr.io/heissonwillen/event-go:latest
          cache-to: type=registry,ref=ghcr.io/heissonwillen/event-go:latest