name: Build, test and scan

on:
  pull_request:
    branches:
      - main

jobs:
  build-go:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Build project
        run: go build -o server ./cmd/server/main.go

  test-go:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: go test ./... -v -coverprofile=coverage.out

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: go-code-coverage
          path: coverage.out

      # TODO: update this to different username
      - name: Publish coverage to coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
          github-token: ${{ secrets.GITHUB_TOKEN }}

  scan-vulnerabilities:
    name: Scan for vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Golang security scanner
        uses: securego/gosec@v2.21.4
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      
      # TODO: change where this is uploaded to
      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
