name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Generate new tag and create a new release
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version based on semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create new tag and release based on semver
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: "**Full Changelog**: https://github.com/heissonwillen/event-go/compare/${{ steps.semver.outputs.current }}...${{ steps.semver.outputs.next }}"
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          commit: main
