name: Create GitHub release and publish Docker image 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Generate new tag and create a new release
    runs-on: ubuntu-latest
    permissions:
        contents: write
    outputs:
      semver_next: ${{ steps.semver.outputs.next }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version based on semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create new tag and release based on semver
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: "**Full Changelog**: https://github.com/heissonwillen/event-go/compare/${{ steps.semver.outputs.current }}...${{ steps.semver.outputs.next }}"
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          commit: main
        
  docker:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker meta (tags and labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            heissonwillen/event-go
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ needs.deploy.outputs.semver_next }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.deploy.outputs.semver_next }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
